CREATE TABLE users (

    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    EMAIL VARCHAR(254) NOT NULL,
    PASSWORD VARCHAR(40) NOT NULL,
    NAME VARCHAR(40),
    LASTNAME VARCHAR(40),
    CONSTRAINT USERS_PK PRIMARY KEY (ID),
    CONSTRAINT USERS_EMAIL_UNIQUE UNIQUE (EMAIL)

);

CREATE TABLE shopping_list (

    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    CONSTRAINT SHOPPING_LIST_PK PRIMARY KEY (ID)

);

CREATE TABLE users_shopping_list (

    ID_USER INTEGER NOT NULL,
    ID_SHOPPING_LIST INTEGER NOT NULL,
    CAN_READ BOOLEAN NOT NULL DEFAULT TRUE,
    CAN_WRITE BOOLEAN NOT NULL DEFAULT FALSE,
    IS_OWNER BOOLEAN NOT NULL DEFAULT FALSE,
    ID_CREATION_USER INTEGER NOT NULL,
    ID_LAST_MODIFICATION_USER INTEGER NOT NULL,
    TIMESTAMP_CREATION_DATE TIMESTAMP NOT NULL,
    TIMESTAMP_MODIFICATION_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT USERS_SHOPPING_LISTS_PK PRIMARY KEY (ID_USER, ID_SHOPPING_LIST),
    CONSTRAINT USERS_SHOPPING_LISTS_SHOPPING_LIST_FK FOREIGN KEY (ID_SHOPPING_LIST) REFERENCES shopping_list(ID) ON DELETE CASCADE,
    CONSTRAINT USERS_SHOPPING_LISTS_USER_FK FOREIGN KEY (ID_USER) REFERENCES users (ID) ON DELETE CASCADE,
    CONSTRAINT USERS_SHOPPING_LISTS_CREATION_USER_FK FOREIGN KEY (ID_CREATION_USER) REFERENCES users (ID) ON DELETE CASCADE,
    CONSTRAINT USERS_SHOPPING_LISTS_MODIFICATION_USER_FK FOREIGN KEY (ID_LAST_MODIFICATION_USER) REFERENCES users (ID) ON DELETE CASCADE

);